### ISSUE TITLE
Error : raise Info(template_file + " was not found.", 0)

### ISSUE THREAD

**Issue by alexandre-sallinen** [Pepitoh/VBad#35]
Well, before even beginning to play around it, the program shuts down with this error:
Traceback (most recent call last):
  File "F:\DOSSIER\Github\VBad\VBad.py", line 170, in <module>
    if __name__ == "__main__": main()
  File "F:\DOSSIER\Github\VBad\VBad.py", line 49, in main
    file_type = return_file_type(template_file)
  File "F:\DOSSIER\Github\VBad\VBad.py", line 11, in return_file_type
    raise Info(template_file + " was not found.", 0)
Info
I just try to launch VBad after downloading it...
What did I did wrong ?

**Comment by Pepitoh** [comment]
Hi, 

Please check Readme, you have to modify path in your const.py before launching it.
