### ISSUE TITLE
AttributeError: WordObject instance has no attribute 'doc'

### ISSUE THREAD

**Issue by mattulm** [Pepitoh/VBad#47]
Hi, getting an error I was hoping to get some help with. I am using Office2007, and I know it is not tested against that, but I wanted to try, as this is the clients office version. I have enabled all of the macro allow settings and the trust center. 
The error is below. Any ideas?
(I am a very poor scripter!)

[+] .doc detected
[+] Valid filename_list, 3 .doc will be generated
[+] C:\tmp\VBad\Example\Orignal_VBA\original_vba_prepared.vbs will be obfuscated and integrated in created documents
        [+] Creating Extra_order_promo.doc
                [+] XOR encrypton was selected
                [+] Randomizing variable and function names
                        [+] Randomized trigger function name : ZMIsbnxMTmvTPEZ
                [+] Obfuscation of strings
                [+] Hiding strings from python script
Traceback (most recent call last):
  File "c:\tmp\VBad\VBad.py", line 170, in <module>
    if __name__ == "__main__": main()
  File "c:\tmp\VBad\VBad.py", line 88, in main
    Office_container.Open(template_file)
  File "c:\tmp\VBad\inc\classes.py", line 150, in Open
    self.Close()
  File "c:\tmp\VBad\inc\classes.py", line 241, in Close
    self.doc.Close(SaveChanges=0)
AttributeError: WordObject instance has no attribute 'doc'

**Comment by mattulm** [comment]
Hmm, very weird. Running it again, and it appears to have worked. I still get a popup error from Office complaining that the last time this document was opened it caused Office to crash.
Seems to have generated the macros though.
